# Publish Github workflow artifacts 
name: Publish Github actions artifacts 

on: 
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  archive-build-artifacts:
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Create a temporary artifact downloads Dir
        run: mkdir downloads

      - name: Add artifacts to publish to the temp Dir
        run: | 
          cd downloads
          echo 'alpha' > alpha.html
          echo 'bravo' > bravo.html
          echo 'charlie' > charlie.html
          cd ..

      - name: Use the upload artificat Guthub Action
        uses: actions/upload-artifact@v3
        with: 
          name: assets-for-download
          path: downloads
      - name: Echo out a Git hub Actions secret to the logs
        run: | 
          echo "The Gitgub Actions Secret will be masted: "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trisk to ecgho Github Actions Secret: "
          echo ${{ secrets.SECRET_TOKEN }} | sed 's/./& /g'

      - name: Github Actions if statement (true)
        env: 
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if: env.WHO_TO_TRUST == 'TrustNo1'
        run: echo "I know what the secret token is! "

      - name: Github Actions if statement (false)
        env: 
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if: env.WHO_TO_TRUST != 'TrustNobody'
        run: echo "I was wrong thinking that the secret was TrustNobody! "
      
