# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: DevOps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Run a one line  script
      run: echo "Hello BalBla"

    - name: Run a multi-lines script
      run: |
        echo Wghat is in this Dir
        ls -ltr 
        echo 
        echo Is Java Installed?
        java -version
        echo 
        echo Is Git installed? 
        git --version
        echo What about build tools? 
        mvn --version
        gradle --version
        ant -version
        
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    #     server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    #     settings-path: ${{ github.workspace }} # location for the settings.xml file

    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml

    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
